name: Update README

on:
  push:
    branches: [master]
  workflow_dispatch:  # Manual trigger

jobs:
  reorganize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' 
      - name: Install python dependencies
        run: pip install lupa
      - name: Install lpm
        run: wget https://github.com/lite-xl/lite-xl-plugin-manager/releases/download/latest/lpm.x86_64-linux -O ./lpm-latest && chmod +x ./lpm-latest
      - name: Generate lua files inside the directory parsers
        run: ./lpm-latest --userdir . color install '*'
      - name: Call python code
        run: python3 ./parsers/images/main.py
      - name: Clean up
        run: rm -rf ./colors
      - name: Commit changes
        run: |
            git config --global user.name "Github Actions" && git config --global user.email "<>"
            git add .
            git commit -m '[CI] Updated images'
            git push
