name: Generate Images

on:
  push:
    branches: [master]
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: "0 */6 * * *"

jobs:
  generate_images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install python dependencies
        run: pip install lupa
      - name: Install lpm
        run: wget https://github.com/lite-xl/lite-xl-plugin-manager/releases/download/latest/lpm.x86_64-linux -O ./lpm-latest && chmod +x ./lpm-latest
      - name: Generate lua files inside the directory parsers
        run: ./lpm-latest --userdir . color install '*'
      - name: Remove the images directory if it exists
        run: rm -rf ./parsers/images
      - name: Make the images directory for the python's output
        run: mkdir ./parsers/images
      - name: Call python code
        run: python3 ./parsers/main.py
      - name: Clean up colors directory
        run: rm -rf ./colors
      - name: Clean up lpm directorie
        run: rm -rf ./lpm
      - name: Clean up lpm-latest executable
        run: rm ./lpm-latest
      - name: Config email
        run: git config --global user.name "Github Actions" && git config --global user.email "<>"
      - name: Git add
        run: git add .
      - name: Commit images
        run: git commit -m '[CI] Updated images'
      - name: Push changes
        run: git push
